services:
  - type: static
    name: cloud-resume
    repo: https://github.com/Lavanyajc/cloud-resume
    branch: main
    buildCommand: "echo 'No build step needed for static HTML'"
    staticPublishPath: .
    autoDeploy: true
